<a href="https://colab.research.google.com/github/Rithikap-8/HeartDiseasePrediction-ML/blob/main/NewHeart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/heardiseaseprediction/heart.csv')
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [ ]:

data.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
simple=SimpleImputer(strategy="mean",missing_values=np.nan)
simple.fit(data.iloc[:,4:6])
data.iloc[:,4:6]=simple.transform(data.iloc[:,4:6])

<ipython-input-8-d0c9d4e27df7>:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.iloc[:,4:6]=simple.transform(data.iloc[:,4:6])


In [ ]:
from sklearn.impute import SimpleImputer
simple=SimpleImputer(strategy="mean",missing_values=np.nan)
simple.fit(data.iloc[:,8:9])
data.iloc[:,8:9]=simple.transform(data.iloc[:,8:9])

<ipython-input-9-dc40ba970af6>:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  data.iloc[:,8:9]=simple.transform(data.iloc[:,8:9])


In [ ]:

data

age  sex  cp  trtbps   chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145  233.0  1.0        0       150   0.0      2.3    0   
1     37    1   2     130  250.0  0.0        1       187   0.0      3.5    0   
2     41    0   1     130  204.0  0.0        0       172   0.0      1.4    2   
3     56    1   1     120  236.0  0.0        1       178   0.0      0.8    2   
4     57    0   0     120  354.0  0.0        1       163   1.0      0.6    2   
..   ...  ...  ..     ...    ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140  241.0  0.0        1       123   1.0      0.2    1   
299   45    1   3     110  264.0  0.0        1       132   0.0      1.2    1   
300   68    1   0     144  193.0  1.0        1       141   0.0      3.4    1   
301   57    1   0     130  131.0  0.0        1       115   1.0      1.2    1   
302   57    0   1     130  236.0  0.0        0       174   0.0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [ ]:

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data.iloc[:,2:3]=lb.fit_transform(data.iloc[:,2:3])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data.iloc[:,-1,]=lb.fit_transform(data.iloc[:,-1,])

In [ ]:
#splitting the data into train and test
x=data.iloc[:,1:-1]
x

sex  cp  trtbps   chol  fbs  restecg  thalachh  exng  oldpeak  slp  caa  \
0      1   3     145  233.0  1.0        0       150   0.0      2.3    0    0   
1      1   2     130  250.0  0.0        1       187   0.0      3.5    0    0   
2      0   1     130  204.0  0.0        0       172   0.0      1.4    2    0   
3      1   1     120  236.0  0.0        1       178   0.0      0.8    2    0   
4      0   0     120  354.0  0.0        1       163   1.0      0.6    2    0   
..   ...  ..     ...    ...  ...      ...       ...   ...      ...  ...  ...   
298    0   0     140  241.0  0.0        1       123   1.0      0.2    1    0   
299    1   3     110  264.0  0.0        1       132   0.0      1.2    1    0   
300    1   0     144  193.0  1.0        1       141   0.0      3.4    1    2   
301    1   0     130  131.0  0.0        1       115   1.0      1.2    1    1   
302    0   1     130  236.0  0.0        0       174   0.0      0.0    1    1   

     thall  
0        1  
1        2  
2        2  
3        2  
4        2  
..     ...  
298      3  
299      3  
300      3  
301      3  
302      2  

[303 rows x 12 columns]

In [ ]:

y=data.iloc[:,-1:]
y

output
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

In [ ]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:

x_train,y_train

(     sex  cp  trtbps   chol  fbs  restecg  thalachh  exng  oldpeak  slp  caa  \
 74     0   2     122  213.0  0.0        1       165   0.0      0.2    1    0   
 153    0   2     146  278.0  0.0        0       152   0.0      0.0    1    1   
 64     1   2     140  211.0  1.0        0       165   0.0      0.0    2    0   
 296    0   0     124  197.0  0.0        1       136   1.0      0.0    1    0   
 287    1   1     154  232.0  0.0        0       164   0.0      0.0    2    1   
 ..   ...  ..     ...    ...  ...      ...       ...   ...      ...  ...  ...   
 251    1   0     132  247.0  1.0        0       143   1.0      0.1    1    4   
 192    1   0     120  188.0  0.0        1       113   0.0      1.4    1    1   
 117    1   3     120  193.0  0.0        0       162   0.0      1.9    1    0   
 47     1   2     138  257.0  0.0        0       156   0.0      0.0    2    0   
 172    1   1     120  284.0  0.0        0       160   0.0      1.8    1    0   
 
      thall  
 74       2 

In [ ]:

#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:


y_pred=lr.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:

from sklearn.metrics import r2_score,confusion_matrix,classification_report,accuracy_score
r2_score(y_pred,y_test)

0.3967032967032966

In [ ]:

print(accuracy_score(y_pred,y_test))

0.8524590163934426


In [ ]:
confusion_matrix(y_pred,y_test)

array([[22,  4],
       [ 5, 30]])

In [ ]:

acc=(21+30)/(21+4+6+30)
acc

0.8360655737704918

In [ ]:

print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.81      0.85      0.83        26
           1       0.88      0.86      0.87        35

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



In [ ]:

#using the K-fold validation
from sklearn.model_selection import cross_val_score
accur=cross_val_score(estimator=lr,X=x_train,y=y_train,cv=15)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel

In [ ]:

print("Accuracy {:.2f}%".format(accur.mean()*100))

Accuracy 82.75%


In [ ]:

print("Strandard Deviation:{:.2f}%".format(accur.std()*100))

Strandard Deviation:8.53%


In [ ]:

#grid search
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[0.25,0.5,0.75,1]}]
grid_search=GridSearchCV(estimator=lr,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
grid_search.fit(x_train,y_train)
best_accuracy=grid_search.best_score_
best_parameters=grid_search.best_params_
print("Best Accuarcy:{:.2f}%".format(best_accuracy*100))
print("Best parameters:",best_parameters)

Best Accuarcy:82.65%
Best parameters: {'C': 0.25}


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:

#Support Vector machine
from sklearn.svm import SVC
class2=SVC(kernel="poly")
class2.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='poly')

In [ ]:

y_pred2=class2.predict(x_test)
y_pred2

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.model_selection import cross_val_score
accuracy2=cross_val_score(estimator=class2,X=x_train,y=y_train,cv=10)
print("Accuracy of SVM:{:.2f}%".format(accuracy2.mean()*100))
print("Strandard Deviation of SvM:{:.2f}%".format(accuracy2.std()*100))

Accuracy of SVM:66.10%
Strandard Deviation of SvM:7.67%


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

In [ ]:

from sklearn.model_selection import GridSearchCV
parameters2=[{"C":[0.25,0.5,0.75,1],'kernel':['rbf','linear']}]
grid_search2=GridSearchCV(estimator=class2,param_grid=parameters2,scoring="accuracy",cv=10,n_jobs=-1)
grid_search2.fit(x_train,y_train)
best_accuracy=grid_search2.best_score_
best_parameters=grid_search2.best_params_
print("best_accuracy of svm :{:.2f}%".format(best_accuracy*100))
print("best parameters of svm:",best_parameters)


best_accuracy of svm :82.27%
best parameters of svm: {'C': 0.25, 'kernel': 'linear'}


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:

from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred2,y_test))


0.7213114754098361


In [ ]:
print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

           0       0.56      0.75      0.64        20
           1       0.85      0.71      0.77        41

    accuracy                           0.72        61
   macro avg       0.70      0.73      0.71        61
weighted avg       0.76      0.72      0.73        61



In [ ]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
class3=DecisionTreeClassifier()
class3.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:

y_pred3=class3.predict(x_test)
y_pred3

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:

#k fold classifier
from sklearn.model_selection import cross_val_score
accuracy3=cross_val_score(estimator=class3,X=x_train,y=y_train,cv=10)
print("Accuracy of decision tree {:.2f}%".format(accuracy3.mean()*100))
print("Strandard deviation of decision tree {:.2f}%".format(accuracy3.std()*100))

Accuracy of decision tree 70.70%
Strandard deviation of decision tree 9.70%


In [ ]:

#grid search CV
from sklearn.model_selection import GridSearchCV
parameter3=[{"criterion":['gini','entropy','log_loss']}]
grid_search3=GridSearchCV(estimator=class3,param_grid=parameter3,scoring="accuracy",cv=10,n_jobs=-1)
grid_search3.fit(x_train,y_train)
best_accuracy=grid_search3.best_score_
best_parameters=grid_search3.best_params_
print("Best Accuracy of decision tree {:.2f}%".format(best_accuracy*100))
print("Best paramters:",best_parameters)

Best Accuracy of decision tree 74.47%
Best paramters: {'criterion': 'entropy'}


In [ ]:

from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred3,y_test))

0.7540983606557377


In [ ]:

print(classification_report(y_pred3,y_test))

              precision    recall  f1-score   support

           0       0.74      0.71      0.73        28
           1       0.76      0.79      0.78        33

    accuracy                           0.75        61
   macro avg       0.75      0.75      0.75        61
weighted avg       0.75      0.75      0.75        61



In [ ]:

#Randomforest
from sklearn.ensemble import RandomForestClassifier
class4=RandomForestClassifier(n_estimators=100)
class4.fit(x_train,y_train)

<ipython-input-40-0081c0bf117c>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  class4.fit(x_train,y_train)


RandomForestClassifier()

In [ ]:

y_pred4=class4.predict(x_test)
y_pred4

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:

from sklearn.model_selection import cross_val_score
accuracy4=cross_val_score(estimator=class4,X=x_train,y=y_train,cv=10)
print("Accuracy of random forest {:.2f}%".format(accuracy4.mean()*100))
print("strandard deviation of randomforest {:.2f}%".format(accuracy4.std()*100))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed whe

Accuracy of random forest 82.27%
strandard deviation of randomforest 5.40%


In [ ]:

#grid search CV
from sklearn.model_selection import GridSearchCV
parameters=[{"criterion":['gini','entropy','log_loss'],"n_estimators":[100]}]
grid_search4=GridSearchCV(estimator=class4,param_grid=parameters,scoring="accuracy",cv=10,n_jobs=-1)
grid_search4.fit(x_train,y_train)
best_accuracy=grid_search4.best_score_
best_parameters=grid_search4.best_params_
print("Best Accuracy of random forest {:.2f}%".format(best_accuracy*100))
print("Best parameters of random forest ",best_parameters)

Best Accuracy of random forest 83.53%
Best parameters of random forest  {'criterion': 'entropy', 'n_estimators': 100}


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


In [ ]:

print(accuracy_score(y_pred4,y_test))

0.8852459016393442


In [ ]:

print(classification_report(y_pred4,y_test))

              precision    recall  f1-score   support

           0       0.85      0.88      0.87        26
           1       0.91      0.89      0.90        35

    accuracy                           0.89        61
   macro avg       0.88      0.89      0.88        61
weighted avg       0.89      0.89      0.89        61



In [ ]:

#XG boost classifier
import xgboost as xgb
class5=xgb.XGBClassifier()
class5.fit(x_train,y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:

y_pred5=class5.predict(x_test)
y_pred5

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:
# k fold validation
from sklearn.model_selection import cross_val_score
accuracy5=cross_val_score(estimator=class5,X=x_train,y=y_train,cv=10)
print("Accuracy of xgboost {:.2f}%".format(accuracy5.mean()*100))
print("Strandard deviation of xgboost {:.2f}%".format(accuracy5.std()*100))

Accuracy of xgboost 80.20%
Strandard deviation of xgboost 7.26%


In [ ]:

#grid search cv
from sklearn.model_selection import GridSearchCV
parameters=[{"booster":["gbtree",'gblinear','dart'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
grid_search5=GridSearchCV(estimator=class5,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
grid_search5.fit(x_train,y_train)
best_accuracy=grid_search5.best_score_
best_parameters=grid_search5.best_params_
print("Best Accuracy of xgboost {:.2f}%".format(best_accuracy*100))
print("best parameter of xgboost:",best_parameters)

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:160: UserWarning: [01:31:57] WARNING: /workspace/src/learner.cc:742: 
Parameters: { "gamma" } are not used.

  warnings.warn(smsg, UserWarning)


Best Accuracy of xgboost 81.87%
best parameter of xgboost: {'booster': 'gblinear', 'gamma': 0.1}


In [ ]:

print(accuracy_score(y_pred5,y_test))

0.8032786885245902


In [ ]:

print(classification_report(y_pred5,y_test))

              precision    recall  f1-score   support

           0       0.78      0.78      0.78        27
           1       0.82      0.82      0.82        34

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.80      0.80      0.80        61



In [ ]:

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_pred5,y_test))


[[21  6]
 [ 6 28]]


In [ ]:

# Tuning the logistic regression for the best parameter
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=0.25)
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.25)

In [ ]:

y_pred=lr.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [ ]:

print(accuracy_score(y_pred,y_test))

0.8360655737704918


In [ ]:

#tuning the best parameter for the SVM
from sklearn.svm import SVC
class2=SVC(C=0.75,kernel='linear')
class2.fit(x_train,y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.75, kernel='linear')

In [ ]:

y_pred2=class2.predict(x_test)

In [ ]:

accuracy_score(y_pred2,y_test)


0.819672131147541

In [ ]:

#tuning the best parameter for the decision tree classifier
from sklearn.tree import DecisionTreeClassifier
class3=DecisionTreeClassifier(criterion='gini')
class3.fit(x_train,y_train)



DecisionTreeClassifier()

In [ ]:
y_pred3=class3.predict(x_test)


In [ ]:

accuracy_score(y_pred3,y_test)

0.7868852459016393

In [ ]:

#tuning the parameter for the random forest
from sklearn.ensemble import RandomForestClassifier
class4=RandomForestClassifier(criterion='log_loss',n_estimators=100)
class4.fit(x_train,y_train)

<ipython-input-63-80c16fbc403a>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  class4.fit(x_train,y_train)


RandomForestClassifier(criterion='log_loss')

In [ ]:
y_pred4=class4.predict(x_test)


In [ ]:

accuracy_score(y_pred4,y_test)

0.8688524590163934

In [ ]:

from xgboost.sklearn import XGBClassifier
#tuning the xgboost for the best parameter
import xgboost as xgb
class5=XGBClassifier(booster='gbtree',gamma=0.2)
class5.fit(x_train,y_train)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=0.2, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:

y_pred5=class5.predict(x_test)

In [ ]:

accuracy_score(y_pred5,y_test)

0.7868852459016393

In [ ]:
!pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 46.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 21.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 84.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 4.0 MB/s eta 0:00:00


In [ ]:
#!import streamlit as st

/bin/bash: line 1: import: command not found


In [ ]:
# !import streamlit as st
# import joblib
# import numpy as np

# # Load the saved model
# loaded_model = joblib.load('/content/drive/MyDrive/mode/model1.pkl')  # Replace 'your_model.pkl' with the actual path to your model file

# # Streamlit web app
# st.title("Heart Disease Prediction App")

# st.sidebar.header("Input Features")

# # Create input fields for the 13 features
# age = st.sidebar.slider("Age", 29, 77, 55)
# sex = st.sidebar.selectbox("Sex", ["Male", "Female"])
# cp = st.sidebar.selectbox("Chest Pain Type", ["Typical Angina", "Atypical Angina", "Non-anginal Pain", "Asymptomatic"])
# trtbps = st.sidebar.slider("Resting Blood Pressure (mm Hg)", 94, 200, 125)
# chol = st.sidebar.slider("Serum Cholesterol (mg/dl)", 126, 564, 250)
# fbs = st.sidebar.selectbox("Fasting Blood Sugar > 120 mg/dl", ["No", "Yes"])
# restecg = st.sidebar.selectbox("Resting ECG", ["Normal", "ST-T wave abnormality", "Probable or Definite Left Ventricular Hypertrophy"])
# thalachh = st.sidebar.slider("Maximum Heart Rate Achieved (bpm)", 71, 202, 150)
# exng = st.sidebar.selectbox("Exercise Induced Angina", ["No", "Yes"])
# oldpeak = st.sidebar.slider("ST Depression Induced by Exercise Relative to Rest", 0.0, 6.2, 1.0)
# slp = st.sidebar.selectbox("Slope of the Peak Exercise ST Segment", ["Upsloping", "Flat", "Downsloping"])
# caa = st.sidebar.slider("Number of Major Vessels Colored by Flourosopy", 0, 4, 1)
# thall = st.sidebar.selectbox("Thallium Stress Test Result", ["Normal", "Fixed Defect", "Reversible Defect"])

# # Map categorical inputs to numerical values
# sex = 0 if sex == "Male" else 1
# fbs = 1 if fbs == "Yes" else 0

# cp_mapping = {
#     "Typical Angina": 0,
#     "Atypical Angina": 1,
#     "Non-anginal Pain": 2,
#     "Asymptomatic": 3
# }
# cp = cp_mapping[cp]

# restecg_mapping = {
#     "Normal": 0,
#     "ST-T wave abnormality": 1,
#     "Probable or Definite Left Ventricular Hypertrophy": 2
# }
# restecg = restecg_mapping[restecg]

# slp_mapping = {
#     "Upsloping": 0,
#     "Flat": 1,
#     "Downsloping": 2
# }
# slp = slp_mapping[slp]

# thall_mapping = {
#     "Normal": 0,
#     "Fixed Defect": 1,
#     "Reversible Defect": 2
# }
# thall = thall_mapping[thall]

# # Create a feature vector for prediction
# input_features = [age, sex, cp, trtbps, chol, fbs, restecg, thalachh, exng, oldpeak, slp, caa, thall]

# # Convert the input features to a NumPy array
# input_array = np.array(input_features).reshape(1, -1)

# # Make a prediction
# prediction = loaded_model.predict(input_array)

# # Display the prediction
# st.subheader("Prediction")
# if prediction[0] == 0:
#     st.write("The model predicts NO heart disease.")
# else:
#     st.write("The model predicts heart disease.")


/bin/bash: line 1: import: command not found


NameError: ignored